var FriendConstants = {
  RECEIVE_PENDING_FRIENDSHIP: "RECEIVE_PENDING_FRIENDSHIP",
  REMOVE_FRIENDSHIP: "REMOVE_FRIENDSHIP",
  RECEIVE_FRIEND_REQUESTS: "RECEIVE_FRIEND_REQUESTS"
};

module.exports = FriendConstants;
