var FriendConstants = {
  RECEIVE_PENDING_FRIENDSHIP: "RECEIVE_PENDING_FRIENDSHIP",
  RECEIVE_ACCEPTED_FRIENDSHIP: "RECEIVE_ACCEPTED_FRIENDSHIP",
  REMOVE_FRIENDSHIP: "REMOVE_FRIENDSHIP",
  RECEIVE_FRIEND_REQUESTS: "RECEIVE_FRIEND_REQUESTS",
  RECEIVE_FRIENDS: "RECEIVE_FRIENDS"
};

module.exports = FriendConstants;
