var UserConstants = {
	LOGIN: "LOGIN",
	ERROR: "ERROR",
	LOGOUT: "LOGOUT",
  RECEIVE_DATA: "RECEIVE_DATA",
  RECEIVE_FETCHED_USER: "RECEIVE_FETCHED_USER",
  RECEIVE_FETCHED_USERS: "RECEIVE_FETCHED_USERS"
};

module.exports = UserConstants;
