# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191898233b47df5bb835f18188be9a1ea4af0d74f51afc0434726acb8766c61accfeebae7113ad039eb19eb5bf581631d03aba5b57787364fbd785679a680f4b

test:
  secret_key_base: fc1a88f71649c4c46f7880c0b3b968f58a62bcc480ec1697abdcafc2422c3da1d8c206ab20a964ed42aa0b0772d7c0a1a78795c1817885b7439069d2251dde40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
